<?php

namespace AppBundle\Repository;

/**
 * SujetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SujetsRepository extends \Doctrine\ORM\EntityRepository
{
}
